### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by galeone** [Galeontz/URedis#2]
Add the pre-built files (no headers - they should be shared between all the operating systems) for windows.
Update the build.cs to support this platform

**Comment by EliLentz** [comment]
Hi @galeone,
--
 Can't compile plugin code due to this error. I thought this error only occurs on Linux platforms 🤔.  When I've tried to do plugin by myself only for Windows, I didn't catch it.

 ![image](https://github.com/Galeontz/URedis/assets/71344921/49ecae1f-7c49-4702-882c-7985c238ce1d)
 
Here https://pgaleone.eu/2022/05/27/unreal-engine-third-party-linux-abi-compatibility/ you wrote that I can use `nm` but I don't think it is possible.

Also look at that
--
![image](https://github.com/Galeontz/URedis/assets/71344921/2951bf2e-a678-49e1-8cee-3b9e4043d34c)

I dont have 'BuildSettingsVersion.V5'. Currently I'm using `Latest`. I'll try to figure out how to add fifth build settings version👍

**Comment by galeone** [comment]
About the second one, it's a setting available on unreal engine 5.4 - let's
start supporting from the latest available engine onwards.

For the linking error, it looks like the Windows library you are linking
doesn't contain that symbol that instead is available in the headers. Being
the header added by me on Linux for a specific version of redis (see the
.so committed in the repo, you can see the version), perhaps you can try to
add the same version of the prebuilt library for Windows
